name: Test implementation

# Triggered when code is pushed to any branch in a repository
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ./fakturoid

      - name: Build with Gradle
        run: ./gradlew build -x test
        working-directory: ./fakturoid

      - name: Test library
        run: ./gradlew test
        working-directory: ./fakturoid
